config/routes.rb
Rails.application.routes.draw do
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static_pages#index'

  get 'about' => 'static_pages#about'
  get 'login' => 'static_pages#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to root_path, notice: "#{@car.year} #{@car.make} #{@car.model} created" }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @car.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h4>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :make, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :make, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :model, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :model, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :year, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="page-header">
  <%= link_to cars_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @car, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing car</h1>
</div>

<%= render 'form' %>

app/views/cars/index.html.erb
<div class="page-header">
  <%= link_to new_car_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Car
  <% end %>
  <h1>Listing cars</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
            <th>Price</th>
            <th>Price</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @cars) do |car| %>
            <td><%= car.make %></td>
            <td><%= car.model %></td>
            <td><%= car.year %></td>
            <td><%= number_to_currency(car.price) %></td>
            <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cars/new.html.erb
<div class="page-header">
  <%= link_to cars_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New car</h1>
</div>

<%= render 'form' %>

app/views/cars/show.html.erb
<div class="page-header">
  <%= link_to cars_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_car_path(@car), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show car</h1>
</div>

<dl class="dl-horizontal">
  <dt>Make:</dt>
  <dd><%= @car.make %></dd>

  <dt>Model:</dt>
  <dd><%= @car.model %></dd>

  <dt>Year:</dt>
  <dd><%= @car.year %></dd>

  <dt>Price:</dt>
  <dd><%= @car.price %></dd>

  <dt>Price:</dt>
  <dd><%= @car.price %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Modern Business - Start Bootstrap Template</title>

  <!-- Custom Fonts -->
  <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false
" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DaVinci Motors", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= active_class(root_path) %>"><%= link_to 'Cars', root_path %></li>
        <li class="<%= active_class(about_path) %>"><%= link_to 'About', about_path %></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <a href="portfolio-1-col.html">1 Column Portfolio</a>
            </li>
            <li>
              <a href="portfolio-2-col.html">2 Column Portfolio</a>
            </li>
            <li>
              <a href="portfolio-3-col.html">3 Column Portfolio</a>
            </li>
            <li>
              <a href="portfolio-4-col.html">4 Column Portfolio</a>
            </li>
            <li>
              <a href="portfolio-item.html">Single Portfolio Item</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">

  <%= yield %>
  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Your Website 2014</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

</body>

</html>

app/views/static_pages/about.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">About
      <small>Subheading</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="index.html">Home</a>
      </li>
      <li class="active">About</li>
    </ol>
  </div>
</div>
<!-- /.row -->

<!-- Intro Content -->
<div class="row">
  <div class="col-md-6">
    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
  </div>
  <div class="col-md-6">
    <h2>About Modern Business</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
  </div>
</div>
<!-- /.row -->

<!-- Team Members -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Our Team</h2>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-center">
    <div class="thumbnail">
      <img class="img-responsive" src="http://placehold.it/750x450" alt="">
      <div class="caption">
        <h3>John Smith<br>
          <small>Job Title</small>
        </h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<!-- Our Customers -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Our Customers</h2>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6">
    <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
  </div>
</div>
<!-- /.row -->

app/views/static_pages/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag('mustang1.jpg') %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag('mustang2.jpg') %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag('mustang3.jpg') %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<!-- Page Content -->
<!-- Marketing Icons Section -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Welcome to Mustang World
    </h1>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-check"></i> Bootstrap v3.2.0</h4>
      </div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in
          alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum
          quod?</p>
        <a href="#" class="btn btn-default">Learn More</a>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-gift"></i> Free &amp; Open Source</h4>
      </div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in
          alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum
          quod?</p>
        <a href="#" class="btn btn-default">Learn More</a>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><i class="fa fa-fw fa-compass"></i> Easy to Use</h4>
      </div>
      <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in
          alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum
          quod?</p>
        <a href="#" class="btn btn-default">Learn More</a>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->

<!-- Portfolio Section -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Our Mustangs</h2>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang4.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang5.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang6.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang7.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang4.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
  <div class="col-md-4 col-sm-6">
    <a href="portfolio-item.html">
      <%= image_tag('mustang4.jpg', class: "img-responsive img-portfolio img-hover") %>
    </a>
  </div>
</div>
<!-- /.row -->

<!-- Features Section -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Modern Business Features</h2>
  </div>
  <div class="col-md-6">
    <p>The Modern Business template by Start Bootstrap includes:</p>
    <ul>
      <li><strong>Bootstrap v3.2.0</strong>
      </li>
      <li>jQuery v1.11.0</li>
      <li>Font Awesome v4.1.0</li>
      <li>Working PHP contact form with validation</li>
      <li>Unstyled page elements for easy customization</li>
      <li>17 HTML pages</li>
    </ul>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit,
      quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
  </div>
  <div class="col-md-6">
    <img class="img-responsive" src="http://placehold.it/700x450" alt="">
  </div>
</div>
<!-- /.row -->

<hr>

<!-- Call to Action Section -->
<div class="well">
  <div class="row">
    <div class="col-md-8">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti
        beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
    </div>
    <div class="col-md-4">
      <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a>
    </div>
  </div>
</div>

<hr>

<!-- Footer -->
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Copyright &copy; Your Website 2014</p>
    </div>
  </div>
</footer>

app/views/static_pages/login.html.erb
<%= form_tag login_path, class: "form-horizontal login-form", role: "form" %>

  <div class="form-group">
    <%= label_tag :login, nil, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= text_field_tag :login, nil, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :password, nil, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= password_field_tag :password, nil, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag 'Login', class: "btn btn-success btn-block" %>
    </div>
  </div>